version: '3'

services:
  etl-project:
    image: etl_project_medical:1.0.1
    build: .
    container_name: etl_medical-server
    working_dir: /code
    restart: always
    command: python manage.py runserver -h 0.0.0.0 -p 8080
    volumes:
      - data:/code
    ports:
      - "8010:8080"
volumes:
    data:



