version: '3'

services:
  etl-project:
    image: etl_ai_schedule:1.0.1
    build: .
    container_name: etl_ai_schedule
    working_dir: /code
    restart: always
    command: python manage.py
    volumes:
      - data:/code
volumes:
    data:



